site_name: COMP423 Course Notes
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition

